{
 "title": "SensorPush-VM",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensors",
    "query": "label_values(SensorPush_temperature, sensor_name)"
   }
  ]
 },
 "panels": [
  { "title": "Übersicht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "SensorPush_temperature{sensor_name=~\"$sensors\"}",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(SensorPush_temperature{sensor_name=~\"$sensors\"}[$__rate_interval])",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "avg_over_time(SensorPush_humidity{sensor_name=~\"$sensors\"}[$__rate_interval])",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "expr": "avg_over_time(SensorPush_pressure{sensor_name=~\"$sensors\"}[$__rate_interval])",
     "legendFormat": "{{sensor_name}}"
    }
   ]
  },
  {
   "title": "Derivatives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dewpoint",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "avg_over_time(SensorPush_dewpoint{sensor_name=~\"$sensors\"}[$__rate_interval])",
       "legendFormat": "{{sensor_name}}"
      }
     ]
    },
    {
     "title": "Absolute humidity",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "congm3" } },
     "targets": [
      {
       "expr": "avg_over_time(SensorPush_abs_humidity{sensor_name=~\"$sensors\"}[$__rate_interval])",
       "legendFormat": "{{sensor_name}}"
      }
     ]
    },
    {
     "title": "VPD",
     "type": "timeseries",
     "description": "Vapor Pressure Deficit",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "pressurembar" } },
     "targets": [
      {
       "expr": "avg_over_time(SensorPush_vpd{sensor_name=~\"$sensors\"}[$__rate_interval])",
       "legendFormat": "{{sensor_name}}"
      }
     ]
    },
    {
     "title": "Altitude",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "lengthm" } },
     "targets": [
      {
       "expr": "avg_over_time(SensorPush_altitude{sensor_name=~\"$sensors\"}[$__rate_interval])",
       "legendFormat": "{{sensor_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensor status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Battery voltage",
     "type": "timeseries",
     "description": "This plot shows always the last Voltage value which has been reported to the cloud!",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "avg_over_time(SensorPush_V_voltage{sensor_name=~\"$sensors\"}[$__rate_interval])",
       "legendFormat": "{{sensor_name}}"
      }
     ]
    },
    {
     "title": "RSSI",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "avg_over_time(SensorPush_V_rssi{sensor_name=~\"$sensors\"}[$__rate_interval])",
       "legendFormat": "{{sensor_name}}"
      }
     ]
    }
   ]
  }
 ]
}